### ISSUE TITLE
Local development - Fatal error

### ISSUE THREAD

**Issue by charlesjdillon** [washingtonstateuniversity/WSUWP-Plugin-University-Center#33]
Warning: call_user_func_array() expects parameter 1 to be a valid callback, cannot access private method WSUWP_University_Center_Meta::save_object_url() in /var/www/wordpress/wp-includes/plugin.php on line 496

Changing line 150 in WSUWP_University_Center_Meta from private to public solves this problem. Is there a reason to keep that private? If so, should be noted for local development to change line 150 to public to continue.

**Comment by jeremyfelt** [comment]
We're good as soon as I push this release. Thanks!
