### ISSUE TITLE
Provide links to emails and phone

### ISSUE THREAD

**Issue by charlesjdillon** [washingtonstateuniversity/WSUWP-Plugin-University-Center#43]
Emails and phone numbers should be links after being entered. This is more important on the People portion.

**Comment by jeremyfelt** [comment]
This can be adjusted in the Spine Parent Theme (and any child themes). https://github.com/washingtonstateuniversity/WSUWP-spine-parent-theme/issues/355

**Comment by patricktokeeffe** [comment]
> This can be adjusted in the Spine Parent Theme

@jeremyfelt Is this true for Spine 2.0.1.1 (with Rainier additional styling)? If so can you elaborate on how to enable the adjustments?
